name: DEPLOY TEST

on:
  push:
    branches:
      - main
env:
  AUTH_SECRET: "aB70zSG63WNifaIuzkjKT4u5RloH9VY5ySC9QCN4GoE="
  AUTH_DISCORD_ID: "1380473007771750462"
  AUTH_DISCORD_SECRET: "3976730fcda219040d1358c57e1ecdafabc71e85c8895364a37eef99dacb820a"
  DATABASE_URL: "postgresql://postgres.oxubmywvdkdwhdleitzq:BobbyDB3002@aws-0-us-east-2.pooler.supabase.com:5432/postgres"
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
      
     
      - name: Build the project
        run: npm run build

       

      - name: Install Vercel CLI
        run: npm install -g vercel@latest 

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment production

      - name: Deploy to Vercel
        run: vercel --prod --confirm --token ${{ secrets.VERCEL_TOKEN }}

      
      - name: Create preview deployment
        run: vercel --prod --confirm --token ${{ secrets.VERCEL_TOKEN }} --previews
