name: DEPLOY TEST

on:
  push:
    branches:
      - main
env:
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
  AUTH_DISCORD_ID: ${{ secrets.AUTH_DISCORD_ID }}
  AUTH_DISCORD_SECRET: ${{ secrets.AUTH_DISCORD_SECRET }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
      
     
      - name: Build the project
        run: npm run build

       

      - name: Install Vercel CLI
        run: npm install -g vercel@latest 

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment production --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel --prod --confirm --token ${{ secrets.VERCEL_TOKEN }}

